baseURL = ""
relativeURLs = "True"
copyright = "De Leidsche Flesch"
locale = 'en-us'
title = 'BAPC 2026'
theme = 'ananke'

[params]
    favicon = "/images/logo-blanco.webp"
    site_logo = "/images/logo-blanco.webp"
    mainSections = ['news']
    background_color_class = "bg-red"
[languages]
  [languages.en]
    name="English"
    weight = 1
   [languages.nl]
    name = "Nederlands"
    weight = 2
   [languages.nl.params]
    read_more_copy = "Lees meer!"
  [[languages.en.menus.main]]
    name = "Jury Advice ⬀"
    weight = 6
    identifier = "GitHub"
    url = "https://jury.bapc.eu/advice/"
   [[languages.nl.menus.main]]
    name = "Jury Advies ⬀"
    weight = 6
    identifier = "GitHub"
    url = "https://jury.bapc.eu/advice/"
    
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files